version: 0.2

env:
  variables:
    ACCOUNT_ID: 216989142685
    REGION: us-east-1
    REPO_NAME: test
    IMAGE_TAG: latest1
    IMAGE_URI: 216989142685.dkr.ecr.us-east-1.amazonaws.com/test:latest1

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven docker

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo Building JAR inside app-tier...
      - cd app-tier
      - mvn clean package -DskipTests
      - echo Running SonarQube analysis...
      - mvn clean verify sonar:sonar -Dsonar.projectKey=TODO -Dsonar.host.url=http://3.83.232.209 -Dsonar.login=sqp_9aef180c6bef97fc3f3a94b811ec6ae0e54dbb06
      - echo Building Docker image...
      - docker build -t $REPO_NAME:$IMAGE_TAG .
      - docker tag $REPO_NAME:$IMAGE_TAG $IMAGE_URI
      - cd ..

  post_build:
    commands:
      - echo Pushing image to Amazon ECR...
      - docker push $IMAGE_URI
      - echo Preparing Kubernetes manifests...
      - mkdir -p k8s-out
      - sed "s|IMAGE_PLACEHOLDER|$IMAGE_URI|g" k8s/deployment.yaml > k8s-out/deployment.yaml
      - cp k8s/service.yaml k8s-out/service.yaml
      - echo Done preparing artifacts.

artifacts:
  base-directory: k8s-out
  files:
    - deployment.yaml
    - service.yaml
